### PR TITLE
Add a Github Action to automatically deploy on Github Pages

### PR DESCRIPTION
**Pull request by julienma**
Then you just need to point a custom domain to your git repo, and it's online.

### CODE REVIEW

**Comment by tmosmant** [comment]
Hi @julienma, thank you for this.
I didn't have a very good experience with the GitHub Actions in the past, I find it unreliable, but let's try this!
Could you update it with the version 4.0.0 of [github-pages-deploy-action](https://github.com/JamesIves/github-pages-deploy-action)?

**Comment by julienma** [comment]
@tmosmant thanks, done!

**Comment by tmosmant** [comment]
Even after enabling GitHub pages in the settings of this repo, I still get a 404 [here](https://getluko.github.io/Covid19-French-Auth/). Am I missing something or should I wait a bit more?

**Comment by julienma** [comment]
🎉 I do have a page on https://getluko.github.io/Covid19-French-Auth/

image

It can take a few minutes to deploy. You can check the status right next to the repo name:
image

Here's the build log: https://github.com/GetLuko/Covid19-French-Auth/runs/1894546118

**Pull request merged**
